language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - export PYTHONPATH=.
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
#before_script:
#  - flake8 careful_forms --ignore=E501
# disabled because of W806 bug in pyflakes
script:
  - DJANGO_SETTINGS_MODULE=careful_forms.test_settings coverage run --branch --source=careful_forms $(which nosetests) careful_forms
  - DJANGO_SETTINGS_MODULE=careful_forms.test_settings_disabled coverage run -a --branch --source=careful_forms $(which nosetests) careful_forms
  - coverage report --omit=careful_forms/test*
env:
  - DJANGO=1.3.1
  - DJANGO=1.4
branches:
  only:
    - develop
